### ISSUE TITLE
Последний билд

### ISSUE THREAD

**Issue by vasyaabr** [ivankaurov/ClimbingCompetition#4]
Не могли бы вы опубликовать последний рабочий билд, чтобы желающим не приходилось собирать из исходников самостоятельно? Я поискал, но не нашел.
Спасибо!

**Comment by ivankaurov** [comment]
Лежит тут: https://github.com/ivankaurov/ClimbingCompetition/releases/download/v18.2-rc2/ClimbingCompetition-18.2-rc2.msi
